apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: log-output-claim
      containers:
        - name: logwatcher
          image: mikkolep/logwatcher:v3
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
        #        - name: timestampgenerator
        #          image: mikkolep/timestampgenerator:v2
        #          imagePullPolicy: Always
        #          volumeMounts:
        #            - name: shared-logs
        #              mountPath: /usr/src/app/files