apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: logwatcher
          image: mikkolep/logwatcher:v3
          imagePullPolicy: Always
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: MESSAGE