apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: log-output
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - port: 4001
      protocol: TCP
      targetPort: 4000