apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: mikkolep/pingpong:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: postgres-db-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: POSTGRES_PASSWORD