apiVersion: v1
kind: Service
metadata:
  name: pingpong-service
  namespace: log-output
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 6000