apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc-lb
  namespace: log-output
spec:
  type: LoadBalancer
  selector:
    app: pingpong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 6000