apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: log-output
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
    - name: http
      port: 4001
      protocol: TCP
      targetPort: 6000