apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: db-hpa
  namespace: todoapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postgresql-db
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 25