apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-frontend
  namespace: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app-frontend: todoapp-frontend
  template:
    metadata:
      labels:
        app-frontend: todoapp-frontend
    spec:
      containers:
        - name: todoapp-frontend
          image: mikkolep/todoapp-frontend:v1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "250m"
              memory: "1000Mi"
          ports:
            - containerPort: 3000