apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-backend
  namespace: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app-backend: todoapp-backend
  template:
    metadata:
      labels:
        app-backend: todoapp-backend
    spec:
      containers:
        - name: todoapp-backend
          image: mikkolep/todoapp-backend:v1
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            httpGet:
              path: /healthz
              port: 5000
          resources:
            limits:
              cpu: "150m"
              memory: "200Mi"
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: postgres-db-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: POSTGRES_PASSWORD