apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todoapp-ingress
  namespace: todoapp
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todoapp-frontend-svc
                port:
                  number: 3001
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: todoapp-svc
                port:
                  number: 5001