apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgresql.yaml
  - postgresql-configmap.yaml
  - postgresql-service.yaml
  - secret.yaml
  - analysistemplate.yaml
  - api-service.yaml
  - deployment-backend.yaml
  - service-frontend.yaml
  - ingress.yaml
  - deployment-frontend.yaml
  - deployment-broadcaster.yaml


