apiVersion: v1
kind: Service
metadata:
  name: todoapp-svc
  namespace: todoapp
spec:
  type: ClusterIP
  selector:
    app-backend: todoapp-backend
  ports:
    - port: 5001
      protocol: TCP
      targetPort: 5000