name: Release TodoApp

on:
  push:
    branches:
      - master
    paths:
      - 'TodoApp/backend/**'
      - 'TodoApp/frontend/**'
      - 'TodoApp/Broadcaster/**'
      - '.github/workflows/todoapp-gitops.yaml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: TodoApp/backend
          push: true
          tags: mikkolep/todoapp-backend:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Update yamls
        working-directory: TodoApp/manifests
        run: |-
          kustomize edit set image TODOAPP_BACKEND_IMAGE_PLACEHOLDER=mikkolep/todoapp-backend:${{ github.sha }}

      # Commit and push
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'TodoApp/manifests/kustomization.yaml'
          message: New version release for gitops-app ${{ github.sha }} available
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}